//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsung_Jellyfin_Installer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Samsung_Jellyfin_Installer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges are required to create the folder. Please create it manually or rerun the application as Administrator..
        /// </summary>
        public static string AdminPrivRequired {
            get {
                return ResourceManager.GetString("AdminPrivRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. en | da | nl.
        /// </summary>
        public static string AudioLanguage {
            get {
                return ResourceManager.GetString("AudioLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Tizen Package manager.
        /// </summary>
        public static string CheckingPackageManagerList {
            get {
                return ResourceManager.GetString("CheckingPackageManagerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Tizen CLI....
        /// </summary>
        public static string CheckingTizenCli {
            get {
                return ResourceManager.GetString("CheckingTizenCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Tizen OS version....
        /// </summary>
        public static string CheckTizenOS {
            get {
                return ResourceManager.GetString("CheckTizenOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose release....
        /// </summary>
        public static string ChooseRelease {
            get {
                return ResourceManager.GetString("ChooseRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose TV....
        /// </summary>
        public static string ChooseTV {
            get {
                return ResourceManager.GetString("ChooseTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose version....
        /// </summary>
        public static string ChooseVersion {
            get {
                return ResourceManager.GetString("ChooseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.json not found in the extracted package..
        /// </summary>
        public static string ConfigFailure {
            get {
                return ResourceManager.GetString("ConfigFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to device....
        /// </summary>
        public static string ConnectingToDevice {
            get {
                return ResourceManager.GetString("ConnectingToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Author CSR....
        /// </summary>
        public static string CreateAuthorCsr {
            get {
                return ResourceManager.GetString("CreateAuthorCsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Distributor CSR with DUID....
        /// </summary>
        public static string CreateDistributorCSR {
            get {
                return ResourceManager.GetString("CreateDistributorCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the signed P12 files....
        /// </summary>
        public static string CreateNewCertificates {
            get {
                return ResourceManager.GetString("CreateNewCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung Developer mode IP doesn&apos;t match this devices local IP, do you wish to continue?.
        /// </summary>
        public static string DeveloperIPMismatch {
            get {
                return ResourceManager.GetString("DeveloperIPMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung TV is not in developer mode....
        /// </summary>
        public static string DeveloperModeRequired {
            get {
                return ResourceManager.GetString("DeveloperModeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp; Install.
        /// </summary>
        public static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed....
        /// </summary>
        public static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed:.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading package....
        /// </summary>
        public static string DownloadingPackage {
            get {
                return ResourceManager.GetString("DownloadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading installer....
        /// </summary>
        public static string DownloadingSetupFile {
            get {
                return ResourceManager.GetString("DownloadingSetupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was canceled or failed....
        /// </summary>
        public static string FailedAuthCode {
            get {
                return ResourceManager.GetString("FailedAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load releases:.
        /// </summary>
        public static string FailedLoadingReleases {
            get {
                return ResourceManager.GetString("FailedLoadingReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove old app version.
        /// </summary>
        public static string FailedRemoveOld {
            get {
                return ResourceManager.GetString("FailedRemoveOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove the old Jellyfin app by hand from the TV.
        /// </summary>
        public static string FailedRemoveOldExtra {
            get {
                return ResourceManager.GetString("FailedRemoveOldExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a SDB Server already running, failed to stop....
        /// </summary>
        public static string FailedToStopSdbServer {
            get {
                return ResourceManager.GetString("FailedToStopSdbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDB Server failed to stop!.
        /// </summary>
        public static string FailedToStopSdbServerTitle {
            get {
                return ResourceManager.GetString("FailedToStopSdbServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating keypair.
        /// </summary>
        public static string GenKeyPair {
            get {
                return ResourceManager.GetString("GenKeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating random password....
        /// </summary>
        public static string GenPassword {
            get {
                return ResourceManager.GetString("GenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failed....
        /// </summary>
        public static string InitializationFailed {
            get {
                return ResourceManager.GetString("InitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed.
        /// </summary>
        public static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation may have failed.
        /// </summary>
        public static string InstallationMaybeFailed {
            get {
                return ResourceManager.GetString("InstallationMaybeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation successful.
        /// </summary>
        public static string InstallationSuccessful {
            get {
                return ResourceManager.GetString("InstallationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfin has been successfully installed!.
        /// </summary>
        public static string InstallationSuccessfulOn {
            get {
                return ResourceManager.GetString("InstallationSuccessfulOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Certificate Manager add-on....
        /// </summary>
        public static string InstallingCertificateAddOn {
            get {
                return ResourceManager.GetString("InstallingCertificateAddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Certificate Manager....
        /// </summary>
        public static string InstallingCertificateManager {
            get {
                return ResourceManager.GetString("InstallingCertificateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package on device....
        /// </summary>
        public static string InstallingPackage {
            get {
                return ResourceManager.GetString("InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Tizen Studio CLI....
        /// </summary>
        public static string InstallingSetupFile {
            get {
                return ResourceManager.GetString("InstallingSetupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device IP or device not found..
        /// </summary>
        public static string InvalidDeviceIp {
            get {
                return ResourceManager.GetString("InvalidDeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My IP is not listed....
        /// </summary>
        public static string IpNotListed {
            get {
                return ResourceManager.GetString("IpNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the device&apos;s IP address:.
        /// </summary>
        public static string IpWindowDescription {
            get {
                return ResourceManager.GetString("IpWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter TV IP.
        /// </summary>
        public static string IpWindowTitle {
            get {
                return ResourceManager.GetString("IpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed: Invalid credentials or server error..
        /// </summary>
        public static string JellyfinLoginFailed {
            get {
                return ResourceManager.GetString("JellyfinLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio language preference.
        /// </summary>
        public static string lbl_AudioLanguagePreference {
            get {
                return ResourceManager.GetString("lbl_AudioLanguagePreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto play next episode.
        /// </summary>
        public static string lbl_AutoPlayNextEpisode {
            get {
                return ResourceManager.GetString("lbl_AutoPlayNextEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdrop screensaver.
        /// </summary>
        public static string lbl_BackdropScreensaver {
            get {
                return ResourceManager.GetString("lbl_BackdropScreensaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser settings.
        /// </summary>
        public static string lbl_BrowserSettings {
            get {
                return ResourceManager.GetString("lbl_BrowserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string lbl_Certifcate {
            get {
                return ResourceManager.GetString("lbl_Certifcate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema mode.
        /// </summary>
        public static string lbl_CinemaMode {
            get {
                return ResourceManager.GetString("lbl_CinemaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom WGT.
        /// </summary>
        public static string lbl_CustomWgt {
            get {
                return ResourceManager.GetString("lbl_CustomWgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove old Jellyfin.
        /// </summary>
        public static string lbl_DeletePrevious {
            get {
                return ResourceManager.GetString("lbl_DeletePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details banner.
        /// </summary>
        public static string lbl_DetailsBanner {
            get {
                return ResourceManager.GetString("lbl_DetailsBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was easy, right?.
        /// </summary>
        public static string lbl_easyRight {
            get {
                return ResourceManager.GetString("lbl_easyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable backdrops.
        /// </summary>
        public static string lbl_EnableBackdrops {
            get {
                return ResourceManager.GetString("lbl_EnableBackdrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable external video players.
        /// </summary>
        public static string lbl_EnableExternalVideoPlayers {
            get {
                return ResourceManager.GetString("lbl_EnableExternalVideoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable theme songs.
        /// </summary>
        public static string lbl_EnableThemeSongs {
            get {
                return ResourceManager.GetString("lbl_EnableThemeSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable theme videos.
        /// </summary>
        public static string lbl_EnableThemeVideos {
            get {
                return ResourceManager.GetString("lbl_EnableThemeVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string lbl_expires {
            get {
                return ResourceManager.GetString("lbl_expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve any Jellyfin Users, no Config settings will be changed!.
        /// </summary>
        public static string lbl_FailedUsers {
            get {
                return ResourceManager.GetString("lbl_FailedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Samsung Login.
        /// </summary>
        public static string lbl_ForceLogin {
            get {
                return ResourceManager.GetString("lbl_ForceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfin API Key.
        /// </summary>
        public static string lbl_JellyfinAPIKey {
            get {
                return ResourceManager.GetString("lbl_JellyfinAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfin Config.
        /// </summary>
        public static string lbl_JellyfinConfig {
            get {
                return ResourceManager.GetString("lbl_JellyfinConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lbl_JellyfinServer {
            get {
                return ResourceManager.GetString("lbl_JellyfinServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string lbl_JellyfinServerApi {
            get {
                return ResourceManager.GetString("lbl_JellyfinServerApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfin user(s).
        /// </summary>
        public static string lbl_JellyfinUser {
            get {
                return ResourceManager.GetString("lbl_JellyfinUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lbl_Language {
            get {
                return ResourceManager.GetString("lbl_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Jellyfin Config.
        /// </summary>
        public static string lbl_ModifyConfig {
            get {
                return ResourceManager.GetString("lbl_ModifyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next up enabled.
        /// </summary>
        public static string lbl_NextUpEnabled {
            get {
                return ResourceManager.GetString("lbl_NextUpEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config.
        /// </summary>
        public static string lbl_OpenConfig {
            get {
                return ResourceManager.GetString("lbl_OpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string lbl_Other {
            get {
                return ResourceManager.GetString("lbl_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play default audio track.
        /// </summary>
        public static string lbl_PlayDefaultAudioTrack {
            get {
                return ResourceManager.GetString("lbl_PlayDefaultAudioTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string lbl_Release {
            get {
                return ResourceManager.GetString("lbl_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember audio selections.
        /// </summary>
        public static string lbl_RememberAudioSelections {
            get {
                return ResourceManager.GetString("lbl_RememberAudioSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember IPs.
        /// </summary>
        public static string lbl_RememberIp {
            get {
                return ResourceManager.GetString("lbl_RememberIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember subtitle selections.
        /// </summary>
        public static string lbl_RememberSubtitleSelections {
            get {
                return ResourceManager.GetString("lbl_RememberSubtitleSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-to-left (RTL) reading.
        /// </summary>
        public static string lbl_RTL {
            get {
                return ResourceManager.GetString("lbl_RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TV.
        /// </summary>
        public static string lbl_SelectTv {
            get {
                return ResourceManager.GetString("lbl_SelectTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user(s) to update.
        /// </summary>
        public static string lbl_SelectUsers {
            get {
                return ResourceManager.GetString("lbl_SelectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        public static string lbl_ServerSettings {
            get {
                return ResourceManager.GetString("lbl_ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lbl_Settings {
            get {
                return ResourceManager.GetString("lbl_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip intros.
        /// </summary>
        public static string lbl_SkipIntros {
            get {
                return ResourceManager.GetString("lbl_SkipIntros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle language preference.
        /// </summary>
        public static string lbl_SubtitleLanguagePreference {
            get {
                return ResourceManager.GetString("lbl_SubtitleLanguagePreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle mode.
        /// </summary>
        public static string lbl_SubtitleMode {
            get {
                return ResourceManager.GetString("lbl_SubtitleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what to update.
        /// </summary>
        public static string lbl_UpdateMode {
            get {
                return ResourceManager.GetString("lbl_UpdateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto login.
        /// </summary>
        public static string lbl_userAutoLogin {
            get {
                return ResourceManager.GetString("lbl_userAutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        public static string lbl_UserSettings {
            get {
                return ResourceManager.GetString("lbl_UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Jellyfin Server.
        /// </summary>
        public static string lbl_ValidateJellyfin {
            get {
                return ResourceManager.GetString("lbl_ValidateJellyfin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string lbl_ValidateLogin {
            get {
                return ResourceManager.GetString("lbl_ValidateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🍺 Buy me a beer.
        /// </summary>
        public static string lbl_Validation {
            get {
                return ResourceManager.GetString("lbl_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string lbl_Version {
            get {
                return ResourceManager.GetString("lbl_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading releases....
        /// </summary>
        public static string LoadingReleases {
            get {
                return ResourceManager.GetString("LoadingReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy files to be used in certificate-manager....
        /// </summary>
        public static string MovingP12Files {
            get {
                return ResourceManager.GetString("MovingP12Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device selected.
        /// </summary>
        public static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices found.
        /// </summary>
        public static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices found, retry with virtual NIC?.
        /// </summary>
        public static string NoDevicesFoundRetry {
            get {
                return ResourceManager.GetString("NoDevicesFoundRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Jellyfin server first....
        /// </summary>
        public static string NoJellyfinServer {
            get {
                return ResourceManager.GetString("NoJellyfinServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package to install.
        /// </summary>
        public static string NoPackageToInstall {
            get {
                return ResourceManager.GetString("NoPackageToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring that the output directory exists.
        /// </summary>
        public static string OutputDir {
            get {
                return ResourceManager.GetString("OutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging the wgt file with certificate....
        /// </summary>
        public static string PackagingWgtWithCertificate {
            get {
                return ResourceManager.GetString("PackagingWgtWithCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default path exceeds Windows Path length. Would you like to change it to C:\Tizen Studio Cli?.
        /// </summary>
        public static string PathLengthExceeded {
            get {
                return ResourceManager.GetString("PathLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Path Length Exceeded.
        /// </summary>
        public static string PathLengthWarning {
            get {
                return ResourceManager.GetString("PathLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizen CLI is required but not found. Please install Tizen Studio first..
        /// </summary>
        public static string PleaseInstallTizen {
            get {
                return ResourceManager.GetString("PleaseInstallTizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting to Samsung author endpoint....
        /// </summary>
        public static string PostAuthorCSR {
            get {
                return ResourceManager.GetString("PostAuthorCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting to Samsung distributor....
        /// </summary>
        public static string PostDistributorCSR {
            get {
                return ResourceManager.GetString("PostDistributorCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for use....
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving device address....
        /// </summary>
        public static string RetrievingDeviceAddress {
            get {
                return ResourceManager.GetString("RetrievingDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TV&apos;s found, want to search again with virtual network cards included in the search?.
        /// </summary>
        public static string RetySearchMsg {
            get {
                return ResourceManager.GetString("RetySearchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning network for Samsung TV....
        /// </summary>
        public static string ScanningNetwork {
            get {
                return ResourceManager.GetString("ScanningNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select certificate.
        /// </summary>
        public static string SelectCertificate {
            get {
                return ResourceManager.GetString("SelectCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subtitle Mode.
        /// </summary>
        public static string SelectSubtitleMode {
            get {
                return ResourceManager.GetString("SelectSubtitleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme.
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select WGT and/or TPK file(s).
        /// </summary>
        public static string SelectWGT {
            get {
                return ResourceManager.GetString("SelectWGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string ServerIP {
            get {
                return ResourceManager.GetString("ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing Tizen certificate manager....
        /// </summary>
        public static string SettingCertificateManager {
            get {
                return ResourceManager.GetString("SettingCertificateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting CA certificates....
        /// </summary>
        public static string SettingsCaCerts {
            get {
                return ResourceManager.GetString("SettingsCaCerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully obtained authorization code.
        /// </summary>
        public static string SuccessAuthCode {
            get {
                return ResourceManager.GetString("SuccessAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizen CLI installation failed....
        /// </summary>
        public static string TizenCliFailed {
            get {
                return ResourceManager.GetString("TizenCliFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV duid could not be found....
        /// </summary>
        public static string TvDuidNotFound {
            get {
                return ResourceManager.GetString("TvDuidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Name could not be found....
        /// </summary>
        public static string TvNameNotFound {
            get {
                return ResourceManager.GetString("TvNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update mode.
        /// </summary>
        public static string UpdateMode {
            get {
                return ResourceManager.GetString("UpdateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating certificate profile....
        /// </summary>
        public static string UpdatingCertificateProfile {
            get {
                return ResourceManager.GetString("UpdatingCertificateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using custom WGT file.
        /// </summary>
        public static string UsingCustomWGT {
            get {
                return ResourceManager.GetString("UsingCustomWGT", resourceCulture);
            }
        }
    }
}
